# Generated by Django 4.2.18 on 2025-06-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0004_jobapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
    ]
